services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    env_file:
      - ./cloudflare.env   # <-- Clearly points to your new .env file
    environment:
      - ZONE=qompass.ai
      - RRTYPE=AAAA
      - SUBDOMAIN=@
      - PROXIED=true
  
  #rose:
   # build: ./rose  # Adjust this path if necessary
    #container_name: rose
    #image: rose:latest
    #restart: unless-stopped
    #ports:
     # - "11434:11434"  # Adjust if needed; this is where it will be exposed
    #volumes:
     # - ./rose:/app  # Adjust based on where your `rose` files are
    #environment:
    #  - ROSE_ENV=production
    #  - ROSE_HOST=0.0.0.0:11434
    #  - ROSE_CONFIG_PATH=/app/config
    #  - ROSE_MODEL_PATH=/app/models
    #  - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    #runtime: nvidia
    networks:
      - quantum-net

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - land
      #- rose
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/qompass.ai:ro
    networks:
      - quantum-net

  cloudflared:
    build: ./cloudflared
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - /home/phaedrus/.cloudflared:/home/phaedrus/.cloudflared
      - /home/phaedrus/.cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    environment:
      - TUNNEL_ORIGIN_CERT=/home/phaedrus/.cloudflared/cert.pem
    command: cloudflared tunnel run qompass
    networks:
      - quantum-net

  land:
    build: ./land
    container_name: land
    restart: unless-stopped
    environment:
      - OQS_PROVIDER=openssl
      - SSL_CIPHERS=KYBER-768:ECDHE-ECDSA-AES256-GCM-SHA384
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - quantum-net

networks:
  quantum-net:
    driver: bridge
    enable_ipv6: true

