  auth-github:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy-github
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=GITHUB_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=GITHUB_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=32_byte_secret
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://ahoy:9000
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
    ports:
      - "4180:4180"
    networks:
      - quantum-net

  auth-google:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy-google
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=GOOGLE_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=GOOGLE_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=32_byte_secret
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://ahoy:9000
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4181
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
    ports:
      - "4181:4181"
    networks:
      - quantum-net

  auth-microsoft:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy-microsoft
    environment:
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_CLIENT_ID=AZURE_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=AZURE_CLIENT_SECRET
      - OAUTH2_PROXY_TENANT=common
      - OAUTH2_PROXY_COOKIE_SECRET=32_byte_secret
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://ahoy:9000
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4182
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
    ports:
      - "4182:4182"
    networks:
      - quantum-net

